CREATE TABLE finance (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    amount NUMERIC(19,2) NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    type TEXT NOT NULL
)